### ISSUE TITLE
Board 0.0.8 bootet nur mit Reset-Taste an USB und Logamatic

### ISSUE THREAD

**Issue by mutex1980** [the78mole/km271-wifi#6]
Hallo,

was kann ich tun, wenn das Board (Rev. 0.0.8) am USB nur in den seltensten Fällen und in der Logamatic nie beim Power-On booted? Ich muss immer die Reset Taste drücken ab dann funktioniert Alles einwandfrei.

Danke und Gruß,
Mirko

**Comment by mutex1980** [comment]
Ok schein ein Duplikat zu sein:

https://github.com/dewenni/ESP_Buderus_KM271/issues/99

**Comment by the78mole** [comment]
Hallo Mirko,

irgendwie verstehe ich Deinen Satz nicht ganz... Da kommt zwei Mal "am USB" vor... Ich nehme einfach mal an, eines davon meint: In der Buderus. Ich vermute, Du setzt auch den Power Jumper jeweils richtig auf USB oder Buderus, oder?

Grüße,
Daniel

**Comment by mutex1980** [comment]
> Hallo Mirko,
> 
> irgendwie verstehe ich Deinen Satz nicht ganz... Da kommt zwei Mal "am USB" vor... Ich nehme einfach mal an, eines davon meint: In der Buderus. Ich vermute, Du setzt auch den Power Jumper jeweils richtig auf USB oder Buderus, oder?
> 
> Grüße, Daniel

Ja Du hast Recht, sorry, ich habe den originalen Satz korrigiert. Es sind beide Fälle gemeint USB und Logamatic.

**Comment by the78mole** [comment]
Hallo Mirko,

Naja, man kann das Board ja auch über USB versorgen, wenn es in der Buderus steckt, dann muss der Jumper auch pben auf USB stecken, sonst kann man sich den USB sparen :-)
Aber so ein Verhalten (Power-On-Reset funktioniert nicht) habe ich tatsächlich noch nicht erlebt. Welche Firmware hast Du denn auf dem Board? Die ESPhome oder die von dewenni?

Grüße,
Daniel

**Comment by mutex1980** [comment]
Das ist die von dewenni 4.1.0

**Comment by DonCanDo** [comment]
Moin, 

ich hab das Problem leider auch. Hattest du dann eine Lösung gefunden?

**Comment by the78mole** [comment]
Nachdem es ein issue von dewenni gewesen zu sein scheint, schließe ich das hier...

**Comment by Manawyrm** [comment]
> Nachdem es ein issue von dewenni gewesen zu sein scheint, schließe ich das hier...

Bin ich mir leider nicht so sicher, ich konnte das jetzt leider schon mehrfach beobachten, dass die km271-wifi nicht mit der Buderus zusammen startet :( 

Ich könnte da jetzt vermutlich irgendwelche kruden Hacks machen, aber vielleicht hast du eine bessere Idee? 
@DonCanDo Wie sieht's bei dir aus, hast du eine Lösung gefunden?

**Comment by DonCanDo** [comment]
Hey Hey. Ich habe an meinem Dieselmonster eine Aufputz Steckdose mit USB angebunden und das KM271 wird dort mit Strom versorgt. Ich habe mich dann damit getröstet dass ich über den anderen USB laden kann wenn ich im Keller acker und die Steckdose ein Backup im Keller ist weil ich die Heizung seperat verkabelt habe. Das Modul arbeitet brav und fleißig selbst mit meinem... leider maroden.. Homeassistent wegen der blöden SSD die nach einem Jahr Stress macht usw...... Das einzige ist die Abgastemperatur. Die haut immer 250° Peaks raus. Sensor schon 3 mal getauscht keine Lösung. Fehler Tage 0. Vielleicht hat da jemand eine Ahnung mit einem festen widerstand simulieren konnte ich noch nicht machen weil mir noch nicht klar ist wie der Abgastemperatur Sensor in der Regelung eingebunden ist.
