### ISSUE TITLE
I have a version 0.0.5:

### ISSUE THREAD

**Issue by gtsy7** [the78mole/km271-wifi#7]
you can send me the last one, I'll print it myself, otherwise I can't connect to the lan W5500 Ethernet
![271](https://github.com/user-attachments/assets/5c42c68c-a254-465e-b2ba-e9803f284908)

**Comment by the78mole** [comment]
???

**Comment by gtsy7** [comment]
can you send me the PCB file?

**Comment by the78mole** [comment]
Please download KiCad (it's Open Source) and Export the files you need.

**Comment by gtsy7** [comment]
where can I download it?

**Comment by gtsy7** [comment]
> Загрузите KiCad (это ПО с открытым исходным кодом) и экспортируйте необходимые вам файлы.

ок thanks

**Comment by the78mole** [comment]
From this repo?
